---
#
# Installing Filebeat
#

# Install Filebeat 

- name: Install Filebeat with apt
  get_url:
   url: "{{ DOWNLOAD_URL }}"
   dest: "{{ INSTALLATION_DIR }}"

- name: Isntalling Filebeat
  command: sudo dpkg -i {{ INSTALLATION_DIR }}/{{ BEATS }}-{{ BEATS_VERSION }}-amd64.deb

- name: Copy filebeat config file for nginx
  template:
    src: filebeat.yml
    dest: "{{ BEATS_HOME }}/filebeat.yml"

# Starting Filebeat

- name: Starting Filebeat
  service:
   name: filebeat
   state: started

# - name: Installing nginx modules
#   command: sudo filebeat modules enable nginx

# - name: Installing system modules
#   command: sudo filebeat modules enable system

