---
#
# Installing Filebeat
#

# Install Filebeat 

- name: Install Filebeat with apt
  get_url:
   url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.5.0-amd64.deb"
   dest: ./

- name: Isntalling Filebeat
  command: sudo dpkg -i /home/ubuntu/filebeat-7.5.0-amd64.deb

- name: Copy filebeat config file for nginx
  template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

# Starting Filebeat

- name: Starting Filebeat
  service:
   name: filebeat
   state: started

# - name: Installing nginx modules
#   command: sudo filebeat modules enable nginx

# - name: Installing system modules
#   command: sudo filebeat modules enable system

