---

# Installing Logstash
#
#
- name: Download Logstash
  get_url:
   url: "{{ DOWNLOAD_URL }}"
   dest: "{{ INSTALLATION_DIR }}"

# Installing Logstash
#
- name: Install Logstash
  command: sudo dpkg -i {{ INSTALLATION_DIR }}/logstash-{{ LOGSTASH_VERSION}}.deb

 
# Start the service
- name: Starting Logstash
  service:
    name: logstash
    state: started

# - name: Copy a sample apache.log
#   copy:
#     src: ./apache.log
#     dest: ./apache.log

- name: Copy logstash config file for apache
  copy:
    src: nginx.conf
    dest: "{{ LOGSTASH_HOME }}/conf.d/nginx.conf"

- name: Restart logstash
  service:
     name: logstash
     state: restarted
